import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { extractLectora } from "../src/extract/lectora.ts";
import { importPackage } from "../src/import.ts";
import { walk } from "../src/write.ts";

const tmp = () => mkdtempSync(join(tmpdir(), "praxity-import-lectora-"));

function files(dir: string, entries: Record<string, string>) {
	for (const [rel, content] of Object.entries(entries)) {
		mkdirSync(join(dir, rel, ".."), { recursive: true });
		writeFileSync(join(dir, rel), content);
	}
}

type Obj = { html?: string; raw?: string; css?: string; cw?: string; data?: unknown };
type PageSpec = { title: string; idx: number; next: string; decl: Array<[string, string]>; order: string[]; questions?: string; objects: Record<string, Obj> };

/** One page in Lectora's published shape: the head script in pageN.html, the object literals in device_Desktop/pageN.js. */
function page(id: string, p: PageSpec): Record<string, string> {
	const html = `<!DOCTYPE html>
<html lang="en" dir="ltr">
<!-- GENERATED BY:  Lectora Online v 6.2.4(242) (http://www.trivantis.com) -->
<head>
<TITLE>${p.title}</TITLE>
<script>
function trivNextChapter()
{
    trivExitPage('${p.next}', true);
}
if ( is.min )
{
	var rcdObj = { rcdData: {} };
${p.decl.map(([n, c]) => `\tvar ${n} = new ${c}(); //${n}`).join("\n")}
${p.questions ?? ""}
	var arWnds = [${p.order.join(",")}];
}
</script>
</head>
<body><div id="wndPage"></div></body>
</html>`;
	const js = `${Object.entries(p.objects)
		.map(
			([n, o]) => `${n}.rcdData.att_Desktop =
{
	innerHtml:	${o.raw ?? JSON.stringify(o.html ?? "")},
	cssText:	"${o.css ?? "visibility: inherit; position: absolute; left: 10px; top: 10px;"}",
	cssClasses:	"",
	id:		"${n.replace(/\D/g, "")}",
	htmlId:		"tobj${n.replace(/\D/g, "")}",
	bInsAnc:	0,
	cwObj:		${o.cw ?? `{\n\t\t"name":\t"${n}"\n\t}`},
	objData:	${JSON.stringify(o.data ?? { a: [0, 32, 0, [10, 10, 100, 20]] })}
};`,
		)
		.join("\n")}
rcdObj.rcdData.att_Desktop =
{
	focusColor:	"#ff9900",
	focusWidth:	2,
	pageIdx:	${p.idx}
};
rcdObj.preload_Desktop = [];
`;
	return { [`${id}.html`]: html, [`device_Desktop/${id}.js`]: js };
}

const txt = (inner: string) => `<div name="dCon" style="position: absolute;"><div name="dCon2" class="ttxt">${inner}</div></div>`;
/** A text object whose HTML splices a variable's value at runtime, as Lectora writes it. */
const spliced = (before: string, variable: string, after: string) => `${JSON.stringify(txt(before).replace(/<\/div><\/div>$/, ""))} +  ${variable}.getValueForDisplay() + ${JSON.stringify(`${after}</div></div>`)}`;
const action = (name: string, body: string) => `{type:6,on:2,delay:0,name:'${name}',actItem:function(){ ${body} }}`;
const button = (label: string, actions: string[]) => ({
	html: `<div id="x"><svg viewBox="0 0 10 10"><text><tspan x="0" y="0">${label}</tspan></text></svg></div>`,
	cw: `{\n\t\t"name":\t"${label}",\n\t\t"arChld":\n\t[\n\t\t${actions.join(",\n\t\t")}\n\t]\n\t}`,
	data: { a: [4, 33120, 0, [10, 10, 50, 20]], altValue: label, titleValue: label },
});
/** Template objects every page carries: the title text, a skip link and a logo. */
const chromeDecl: Array<[string, string]> = [["text900", "jsWndText"], ["text901", "jsWndText"], ["image902", "jsWndImage"]];
const chromeObjects: Record<string, Obj> = {
	text900: { html: txt('<p><span>Acme Harbour</span></p>') },
	text901: { html: txt('<h1><p><a href="javascript:hyperlink1()">SKIP</a></p></h1>') },
	image902: { html: '<img id="tobj902Img" src="images/logo.png" alt="" title="">' },
};

function lectoraPackage(): string {
	const dir = tmp();
	const testXml = `<?xml version="1.0" encoding="UTF-8"?>
<lectoratest>
<name>Test 1</name>
<passinggrade>70</passinggrade>
<page><index>0</index><name>page2.html</name><id>2</id>
<question><id>21</id><type>2</type><name>Multiple Choice</name><text>Which animal roars?</text><correctans>Lion</correctans><choices>Lion|Mouse</choices><choicefbs>Yes, it does.~|~No, it squeaks.</choicefbs></question>
</page>
<page><index>1</index><name>page3.html</name><id>3</id>
<question><id>31</id><type>5</type><name>Fill in the Blank</name><text>The king of the jungle is the ___.</text><correctans>lion</correctans><choices>lion</choices><choicefbs></choicefbs></question>
</page>
</lectoratest>`;
	files(dir, {
		"trivantis.js": "var is = {min: true};",
		"index.html": `<!DOCTYPE html>\n<html lang="en" dir="ltr">\n<!-- GENERATED BY:  Lectora Online v 6.2.4(242) (http://www.trivantis.com) -->\n<head><title>Harbour Starter</title></head><frameset><frame src="titlemgr.html"/></frameset></html>`,
		"imsmanifest.xml": `<?xml version="1.0"?><manifest identifier="HARBOUR1" version="1.3"><organizations default="o"><organization identifier="o"><title>Harbour Basics</title><item identifier="I1" identifierref="A1"><title>Harbour Basics</title></item></organization></organizations><resources><resource identifier="A1" type="webcontent" href="index.html"><file href="index.html"/></resource></resources></manifest>`,
		"metadata.xml": `<?xml version="1.0" encoding="ISO-8859-1"?><lom><general><title><string language="en">Harbour Basics</string></title><language>en</language><description><string language="en">Learn the harbour.</string></description></general></lom>`,
		"_tobj9.txt": Buffer.from(testXml).toString("base64"),
		"images/logo.png": "png",
		"images/lion.png": "png",
		// Welcome: page title from the variable, an h2, an image, a shape with text, a BEGIN button.
		...page("page1", {
			title: "START HERE",
			idx: 1,
			next: "page2.html",
			decl: [...chromeDecl, ["text11", "jsWndText"], ["text12", "jsWndText"], ["image13", "jsWndImage"], ["shape14", "jsWndShape"], ["textbutton15", "jsWndTextButton"], ["text16", "jsWndText"]],
			order: ["text901", "text11", "text12", "image13", "shape14", "text16", "textbutton15", "text900", "image902"],
			objects: {
				...chromeObjects,
				text11: { raw: spliced(`<h1><p lang="en"><span><span class='VarCurrentPageName'>`, "VarCurrentPageName", "</span></span></p></h1>") },
				text12: { html: txt('<h2><p><span>Check the <b>main</b> valve.</span></p></h2>') },
				image13: { html: '<img id="tobj13Img" src="images/lion.png" alt="A lion resting" title="">' },
				shape14: { html: '<div id="tobj14inner"><svg viewBox="0 0 10 10"><g><path d="M 0 0"></path></g><g><text><tspan x="0" y="0">Side note</tspan></text></g></svg></div>' },
				textbutton15: button("BEGIN", [action("GoToNextPage", "trivExitPage('page4.html',true,false);")]),
				text16: { html: txt("<p><span>“</span></p>"), data: { a: [0, 32, 0, []], bHideFromScrRdr: true } },
			},
		}),
		// Click-to-reveal: a tab button shows hidden text; a list.
		...page("page4", {
			title: "REVEAL",
			idx: 2,
			next: "page2.html",
			decl: [...chromeDecl, ["text41", "jsWndText"], ["textbutton42", "jsWndTextButton"], ["text43", "jsWndText"], ["text44", "jsWndText"]],
			order: ["text901", "text41", "textbutton42", "text43", "text44", "text900", "image902"],
			objects: {
				...chromeObjects,
				text41: { html: txt('<ul><li><span>Gloves</span><br>\n&nbsp;</li><li><span>Boots</span></li></ul>') },
				textbutton42: button("Tab 1", [action("ShowTabContent", "text43.show();"), action("xAPI_Statement", "")]),
				text43: { html: txt("<p><span>Hidden reveal text</span></p>"), css: "visibility: hidden; position: absolute;" },
				text44: { html: txt("<p><span>Visible after the tab</span></p>") },
			},
		}),
		// Test page: multiple choice with radios and labels, hidden feedback swapped by actions.
		...page("page2", {
			title: "MULTIPLE CHOICE",
			idx: 3,
			next: "",
			decl: [...chromeDecl, ["text20", "jsWndText"], ["qu21", "jsWndMultiChoiceQuestion"], ["text22", "jsWndText"], ["text23", "jsWndText"], ["radio24", "jsWndFormRadio"], ["text25", "jsWndText"], ["radio26", "jsWndFormRadio"], ["textbutton27", "jsWndTextButton"], ["text28", "jsWndText"]],
			order: ["text901", "text20", "text22", "text23", "radio24", "text25", "radio26", "textbutton27", "text28", "text900", "image902"],
			questions: `\tgrpAction0 = function(pF){\n    if(!VarQuestion_21.isCorr('\\u004C\\u0069\\u006F\\u006E'))text28.changeContents( "Not quite, look again." ); else if(typeof pF == 'function') pF();\n};\n\tqu21.arChld=[text22,text23,radio24,text25,radio26];\n\tqu21.type=13;\n\tqu21.arChoices=[\n\t\t{ btnnm:"radio24", btn:"tobj24", txt:"tobj23", img:null },\n\t\t{ btnnm:"radio26", btn:"tobj26", txt:"tobj25", img:null }\n\t\t];`,
			objects: {
				...chromeObjects,
				text20: { html: txt("<h1><p><span>1/2 | MULTIPLE CHOICE</span></p></h1>") },
				qu21: { html: "", cw: `{\n\t\t"questType":\t2,\n\t\t"arrAns":\t["\\\\u004C\\\\u0069\\\\u006F\\\\u006E"],\n\t\t"correctFeedbackFunc":\t"action21_1",\n\t\t"varQuest":\tVarQuestion_21\n\t}`, data: { a: [0, 32, 0, []] } },
				text22: { html: txt("<p><span>Which animal <i>roars</i>?</span></p>") },
				text23: { html: `<label for="rad24">${txt("<p><span>Lion</span></p>")}</label>` },
				radio24: { html: '<div><input type="radio" id="rad24" name="rad21" value="Lion" onclick="VarQuestion_21.set(this.value);"></div>' },
				text25: { html: `<label for="rad26">${txt("<p><span>Mouse</span></p>")}</label>` },
				radio26: { html: '<div><input type="radio" id="rad26" name="rad21" value="Mouse" onclick="VarQuestion_21.set(this.value);"></div>' },
				textbutton27: button("SUBMIT", [action("OnMClkProcQ", "qu21.processQuestion();")]),
				text28: { html: txt("<p><span>Great work!</span></p>"), css: "visibility: hidden; position: absolute;" },
			},
		}),
		// Test page: fill in the blank.
		...page("page3", {
			title: "FILL IN THE BLANK",
			idx: 4,
			next: "",
			decl: [...chromeDecl, ["qu31", "jsWndFillBlankQuestion"], ["text32", "jsWndText"], ["entry33", "jsWndFormEntry"]],
			order: ["text901", "text32", "entry33", "text900", "image902"],
			questions: `\tqu31.arChld=[text32,entry33];\n\tqu31.type=13;`,
			objects: {
				...chromeObjects,
				qu31: { html: "", cw: `{\n\t\t"questType":\t5,\n\t\t"arrAns":\t[],\n\t\t"arAnswers":\t["\\\\u006C\\\\u0069\\\\u006F\\\\u006E"]\n\t}`, data: { a: [0, 32, 0, []] } },
				text32: { html: `<label for="rad33">${txt("<legend><p><span>The king of the jungle is the ___.</span></p></legend>")}</label>` },
				entry33: { html: '<input type="text" maxlength="50" id="frmobj33" title="Entry field">' },
			},
		}),
		// Knowledge check outside the test: a dropdown question and a score variable.
		...page("page5", {
			title: "PRACTICE ROUND",
			idx: 5,
			next: "",
			decl: [...chromeDecl, ["qu51", "jsWndMultiChoiceQuestion"], ["text52", "jsWndText"], ["combo53", "jsWndFormList"], ["text54", "jsWndText"]],
			order: ["text901", "text52", "combo53", "text54", "text900", "image902"],
			questions: `\tqu51.arChld=[text52,combo53];\n\tqu51.type=13;\n\tqu51.arChoices=[\n\t\t{ btnnm:null, btn:null, txt:null, img:null },\n\t\t{ btnnm:null, btn:null, txt:null, img:null }\n\t\t];`,
			objects: {
				...chromeObjects,
				qu51: { html: "", cw: `{\n\t\t"questType":\t2,\n\t\t"arrAns":\t["\\\\u0032"]\n\t}`, data: { a: [0, 32, 0, []] } },
				text52: { html: txt("<p><span>How many lions?</span></p>") },
				combo53: { html: '<select name="Question Drop List" id="frmobj53"><option value="1" label="One">One</option><option value="2" label="Two">Two</option></select>' },
				text54: { raw: spliced("<p><span>Your score: ", "Test_1_Score", "%</span></p>") },
			},
		}),
	});
	return dir;
}

test("imports a Lectora publish: title order, chapters, template chrome, reading order, hidden reveals, questions and a test group", async () => {
	const root = lectoraPackage();
	const course = extractLectora(root);
	assert.equal(course.toolVersion, "Lectora Online v 6.2.4(242)");
	assert.equal(course.title, "Harbour Basics");
	assert.equal(course.description, "Learn the harbour.");
	assert.equal(course.locale, "en");
	assert.deepEqual(course.lessons.map((l) => l.title), ["Chapter 1", "Test 1"]);
	assert.deepEqual(course.lessons.map((l) => l.pages.map((p) => p.title)), [["START HERE", "REVEAL"], ["Test 1", "PRACTICE ROUND"]]);
	assert.ok(course.sourceText.includes("Hidden reveal text"), "hidden text is inventoried");
	assert.ok(course.sourceText.includes("Not quite, look again."), "action-driven feedback is inventoried");
	assert.ok(course.sourceText.includes("Yes, it does."), "test choice feedback is inventoried");
	assert.ok(course.sourceText.includes("Tab 1"), "non-navigation button labels are inventoried");
	assert.ok(!course.sourceText.includes("SKIP") && !course.sourceText.includes("BEGIN"), "template chrome and navigation are not");

	const out = join(tmp(), "course");
	const report = await importPackage(root, out);
	assert.equal(report.detected.tool, "lectora");
	const first = readFileSync(join(out, report.lessons[0]?.file ?? ""), "utf8");
	assert.match(first, /^# START HERE\n\n## Check the \*\*main\*\* valve\.\n\n\/assets\/images\/lion\.png\nalt: A lion resting\n\nSide note\n\n--- REVEAL\n\n- Gloves\n- Boots\n\nVisible after the tab\n\nHidden reveal text$/m);
	assert.doesNotMatch(first, /SKIP|Acme Harbour|logo\.png|BEGIN|“/);
	const second = readFileSync(join(out, report.lessons[1]?.file ?? ""), "utf8");
	assert.match(second, /^# Test 1\nas: assessment-group\nshowResultsSummary: true\npassingScore: 70\n\n\*\*1\/2 \| MULTIPLE CHOICE\*\*\n\n## Which animal \*roars\*\?\nas: choice\nscored: true\n\n\(x\) Lion\nfeedback: Yes, it does\.\n\( \) Mouse\nfeedback: No, it squeaks\.\n\nGreat work!\n\n## The king of the jungle is the \S+\.\nas: fill-blank\nscored: true\n\n\{lion\}\n\nclose: assessment-group$/m);
	assert.match(second, /^--- PRACTICE ROUND\n\n## How many lions\?\nas: choice\n\n\( \) One\n\(x\) Two\n\nYour score: %$/m);
	const sources = report.losses.map((l) => `${l.source}/${l.effect}`);
	assert.ok(sources.includes("lectora:theme/approximated"), "chrome recorded in theme loss");
	assert.ok(report.losses.some((l) => l.source === "lectora:action" && l.at === "page4" && l.detail.includes("Tab 1")), "reveal button recorded");
	assert.ok(sources.includes("lectora:hidden/approximated"), "hidden objects recorded");
	assert.ok(sources.includes("lectora:test/approximated"), "merged test pages recorded");
	assert.ok(report.losses.some((l) => l.source === "lectora:variable" && l.detail.includes("Test_1_Score")), "runtime variable recorded");
});

test("Lectora maps page fonts, inline colours and explicitly marked repeated branding", async () => {
	const root = tmp();
	files(root, {
		"trivantis.js": "",
		"trivantisPage.css": 'body {background-color:#eee;font-family:Verdana;color:#999} .ttxt {color:black} /* .ttxt {color:red} */',
		"images/brand.png": "brand",
	});
	for (let i = 1; i <= 3; i++) {
		const spec = page(`page${i}`, {
			title: `Page ${i}`, idx: i, next: "", decl: [["text1", "jsWndText"], ["text2", "jsWndText"], ["shape3", "jsWndShape"], ["image4", "jsWndImage"], ["shape5", "jsWndShape"]],
			order: ["text1", "text2", "shape3", "image4"], objects: {
				text1: { html: txt(`<p style="color:rgb(17, 34, 51)">Body ${i}</p>`) },
				text2: { html: txt(`<h1><span style="font-family: &quot;Lato&quot;, sans-serif">Heading ${i}</span></h1>`) },
				shape3: { html: '<svg><path style="fill: rgb(18, 52, 86);"></path></svg>', cw: '{name:"Header_Background"}', data: { bHideFromScrRdr: true } },
				image4: { html: '<img src="images/brand.png" alt="Brand">', cw: '{name:"Company Logo"}', data: { bHideFromScrRdr: true } },
				shape5: { html: `<svg id="background${i}"><path style="fill: #fefefe;"></path></svg>`, cw: '{name:"Background_Color"}', data: { bHideFromScrRdr: true } },
			},
		});
		spec[`page${i}.html`] = spec[`page${i}.html`]?.replace("</head>", '<link rel="stylesheet" href="trivantisPage.css"><style>@media print {body {color:#f00}} .ttxt {font-family:Inter}</style></head>') ?? "";
		spec[`device_Desktop/page${i}.js`] = spec[`device_Desktop/page${i}.js`]?.replace('focusColor:', 'font:{name:"Open Sans",color:null},\nfocusColor:') + '\nrcdObj.backgrd_Desktop = ["#fafafa","",0,0,1];';
		files(root, spec);
	}
	const course = extractLectora(root);
	assert.deepEqual(course.theme, { density: "compact", blockSpacing: "compact", navigation: "slides", background: "#fefefe", bodyFont: "Open Sans", headingFont: "Lato", text: "#112233", accent: "#123456", logo: "images/brand.png" });
	assert.equal(course.losses.filter((l) => l.source === "lectora:theme" && l.effect === "approximated").length, 1);
	const out = join(tmp(), "course");
	await importPackage(root, out);
	const yaml = readFileSync(join(out, "course.yaml"), "utf8");
	assert.match(yaml, /colorAccent: "#123456"/);
	assert.match(yaml, /logoUrl: \/assets\/images\/brand.png/);
	assert.equal(readFileSync(join(out, "assets/images/brand.png"), "utf8"), "brand");
});

test("Lectora ignores unmarked image filenames and outside stylesheets; font ties use name order", () => {
	const root = lectoraPackage();
	assert.equal(extractLectora(root).theme?.logo, undefined, "logo.png is not an authored logo designation");
	const outside = join(tmp(), "outside.css");
	writeFileSync(outside, '.ttxt{font-family:"Outside Font";color:#123456}');
	symlinkSync(outside, join(root, "linked.css"));
	const html = readFileSync(join(root, "page1.html"), "utf8");
	writeFileSync(join(root, "page1.html"), html.replace("</head>", '<link rel="stylesheet" href="linked.css"></head>'));
	const js = readFileSync(join(root, "device_Desktop/page1.js"), "utf8");
	writeFileSync(join(root, "device_Desktop/page1.js"), js.replace('Check the ', '<span style=\\"font-family:Verdana\\">BBBB</span><span style=\\"font-family:Inter\\">AAAA</span>Check the '));
	assert.equal(extractLectora(root).theme?.headingFont, "Inter");
	assert.notEqual(extractLectora(root).theme?.bodyFont, "Outside Font");
});

test("Lectora excludes recorded page textures while preserving ordinary and edge-to-edge pictures", () => {
	const root = tmp();
	const spec = page("page1", {
		title: "Synthetic page", idx: 1, next: "", decl: [["image1", "jsWndImage"], ["image2", "jsWndImage"], ["image3", "jsWndImage"], ["image4", "jsWndImage"], ["image5", "jsWndImage"]],
		order: ["image1", "image2", "image3", "image4", "image5"], objects: {
			image1: { html: '<img src="images/a.png" alt="">', cw: '{name:"ImagePattern_Title"}', css: 'left:-20px;top:-10px;width:900px;height:700px;' },
			image2: { html: '<img src="images/background.png" alt="Landscape">', cw: '{name:"Photo"}', css: 'left:0px;top:0px;width:800px;height:600px;' },
			image3: { html: '<img src="images/small.png" alt="">', cw: '{name:"ImagePattern_Example"}', css: 'left:20px;top:10px;width:100px;height:100px;' },
			image4: { html: '<img src="images/tile.png" alt="">', cw: '{name:"Image"}' },
			image5: { html: '<img src="images/oversize.png" alt="">', cw: '{name:"Photo"}', css: 'left:-20px;top:-10px;width:900px;height:700px;' },
		},
	});
	spec["device_Desktop/page1.js"] += '\nrcdObj.pgStyle_Desktop = "width:800px;height:600px;";\nrcdObj.backgrd_Desktop = ["#abcdef","images/tile.png",0,0,1];';
	files(root, spec);
	const course = extractLectora(root);
	const images = course.lessons.flatMap((l) => l.pages.flatMap((p) => [...walk(p.blocks)])).filter((b) => b.kind === "image");
	assert.deepEqual(images.map((b) => [b.src, b.layout]), [["images/background.png", "full"], ["images/small.png", "small"], ["images/oversize.png", undefined]]);
	assert.equal(course.theme?.background, "#abcdef");
	assert.equal(course.losses.filter((l) => l.source === "lectora:theme" && l.effect === "approximated").length, 1);
	assert.equal(course.losses.filter((l) => l.source === "lectora:template").length, 0);
	for (const style of ['left:0%;top:0px;width:800px;', 'left:0px;top:0px;width:800%;', 'left:0px;top:0px;width:800px;transform:scale(2);', 'left:0px;top:0px;width:800px;-webkit-transform:scale(2);']) {
		files(root, { "device_Desktop/page1.js": spec["device_Desktop/page1.js"]!.replace('left:0px;top:0px;width:800px;height:600px;', style) });
		const picture = extractLectora(root).lessons[0]!.pages[0]!.blocks.find((b) => b.kind === "image" && b.src === "images/background.png");
		assert.equal(picture?.kind === "image" ? picture.layout : "missing image", undefined, style);
	}
	files(root, { "device_Desktop/page1.js": spec["device_Desktop/page1.js"]!.replace('ImagePattern_Title', 'ImageBG_Title') });
	assert.equal([...walk(extractLectora(root).lessons[0]!.pages[0]!.blocks)].filter((b) => b.kind === "image").length, 3);
});

test("Lectora promotes large pictures behind styled text after chrome filtering", () => {
	const root = tmp();
	const spec: PageSpec = {
		title: "Cover title", idx: 1, next: "", decl: [["image1", "jsWndImage"], ["image2", "jsWndImage"], ["text1", "jsWndText"], ["text2", "jsWndText"], ["text3", "jsWndText"]],
		order: ["text1", "image1", "image2", "text2", "text3"], objects: {
			image1: { html: '<img src="texture.png" alt="">', cw: '{name:"ImagePattern_Title"}', css: "left:0px;top:0px;width:800px;height:600px;z-index:0;" },
			image2: { html: '<img src="photo.png" alt="A landscape">', css: "left:0px;top:0px;width:800px;height:600px;z-index:1;" },
			text1: { html: '<p style="font-size:20px">A short subtitle</p>', css: "left:20px;top:20px;width:500px;height:30px;z-index:2;" },
			text2: { html: '<p style="font-size:48px;color:black">Cover title</p>', css: "left:20px;top:80px;width:700px;height:60px;z-index:3;" },
			text3: { html: '<p style="font-size:16px">Keep this paragraph.</p>', css: "left:20px;top:200px;width:700px;height:30px;z-index:4;" },
		},
	};
	const read = () => {
		const output = page("page1", spec);
		output["device_Desktop/page1.js"] += '\nrcdObj.pgStyle_Desktop = "width:800px;height:600px;";';
		files(root, output);
		return extractLectora(root).lessons[0]!.pages[0]!.blocks;
	};
	assert.deepEqual(read(), [
		{ kind: "heading", level: 1, text: "Cover title", subtitle: "A short subtitle", background: { src: "photo.png", alt: "A landscape", overlay: "light" } },
		{ kind: "paragraph", text: "Keep this paragraph." },
	]);
	const positions = ["text1", "text2", "text3"].map((n) => spec.objects[n]!.css!);
	spec.objects.image2!.css = "left:0px;top:0px;width:800px;height:420px;z-index:1;";
	for (const n of ["text1", "text2", "text3"]) spec.objects[n]!.css = spec.objects[n]!.css!.replace(/top:\d+px/, "top:500px");
	assert.ok(read().every((b) => b.kind !== "heading" || !b.background), "70% picture without overlapping text stays an image");
	["text1", "text2", "text3"].forEach((n, i) => { spec.objects[n]!.css = positions[i]!; });
	for (const css of [
		"left:0px;top:0px;width:300px;height:300px;z-index:1;",
		"left:0px;top:1000px;width:800px;height:600px;z-index:1;",
		"left:0px;top:0px;width:800px;height:600px;z-index:5;",
		"left:0px;top:0px;width:800px;height:600px;z-index:1;transform:rotate(10deg);",
		"left:0px;top:0px;width:100%;height:600px;z-index:1;",
	]) {
		spec.objects.image2!.css = css;
		assert.ok(read().every((b) => b.kind !== "heading" || !b.background), css);
	}
});


test("Lectora hero ranking and overlay inherit recorded page fonts and flat text rules", () => {
	const root = tmp();
	const spec: PageSpec = {
		title: "Inherited styles", idx: 1, next: "", decl: [["image1", "jsWndImage"], ["text1", "jsWndText"], ["text2", "jsWndText"]],
		order: ["image1", "text1", "text2"], objects: {
			image1: { html: '<img src="photo.png" alt="">', css: "left:0px;top:0px;width:800px;height:600px;" },
			text1: { html: '<p style="font-size:20px">Short subtitle</p>', css: "left:20px;top:20px;width:500px;height:30px;" },
			text2: { html: '<p>Inherited title</p>', css: "left:20px;top:80px;width:700px;height:60px;" },
		},
	};
	const read = (font: Record<string, unknown>) => {
		const output = page("page1", spec);
		output["page1.html"] = output["page1.html"]!.replace("</head>", '<style>body {font-size:30px;color:black} .ttxt {font-size:48px;color:white} @media print {.ttxt {font-size:1px;color:black}}</style></head>');
		output["device_Desktop/page1.js"] = output["device_Desktop/page1.js"]!.replace("focusColor:", `font:${JSON.stringify(font)},focusColor:`) + '\nrcdObj.pgStyle_Desktop = "width:800px;height:600px;";';
		files(root, output);
		return extractLectora(root).lessons[0]!.pages[0]!.blocks[0];
	};
	assert.deepEqual(read({}), { kind: "heading", level: 1, text: "Inherited title", subtitle: "Short subtitle", background: { src: "photo.png", alt: "", overlay: "dark" } });
	assert.deepEqual(read({ size: 32, color: "black" }), { kind: "heading", level: 1, text: "Inherited title", subtitle: "Short subtitle", background: { src: "photo.png", alt: "", overlay: "light" } });
});

test("Lectora maps recorded heading sizes, columns and page width without rotating boxes", () => {
	const root = tmp();
	const spec: PageSpec = { title: "Layout", idx: 1, next: "", decl: [["title", "jsWndText"], ["body", "jsWndText"], ["image", "jsWndImage"], ["aside", "jsWndText"]], order: ["title", "body", "aside", "image"], objects: {
		title: { html: '<p style="font-size:40px">Large line</p>', css: "left:0px;top:0px;width:600px;height:60px;" },
		body: { html: '<p style="font-size:20px">Body text</p>', css: "left:0px;top:80px;width:600px;height:40px;" },
		image: { html: '<img src="photo.png" alt="Example">', css: "left:0px;top:200px;width:200px;height:200px;" },
		aside: { html: '<p style="font-size:20px">Alongside</p>', css: "left:220px;top:220px;width:380px;height:40px;" },
	} };
	const read = () => {
		const output = page("page1", spec);
		output["device_Desktop/page1.js"] += '\nrcdObj.pgStyle_Desktop = "width:1000px;height:600px;";';
		files(root, output);
		return extractLectora(root);
	};
	const course = read();
	assert.equal(course.theme?.contentWidth, 1000);
	const blocks = course.lessons[0]!.pages[0]!.blocks;
	assert.deepEqual(blocks.map((b) => b.kind), ["heading", "paragraph", "columns"]);
	assert.ok(blocks[2]?.kind === "columns" && blocks[2].columns[0]?.[0]?.kind === "image");
	spec.objects.image!.css += "transform:rotate(5deg);";
	assert.ok(read().lessons[0]!.pages[0]!.blocks.every((b) => b.kind !== "columns"));
	assert.ok(read().lessons[0]!.pages[0]!.blocks.every((b) => b.kind !== "image" || b.layout === undefined));
	spec.objects.aside!.css = "left:220px;top:450px;width:380px;height:40px;";
	for (const [width, layout] of [[349, "small"], [350, "medium"], [600, undefined]] as const) {
		spec.objects.image!.css = `left:0px;top:200px;width:${width}px;height:200px;`;
		assert.equal(read().lessons[0]!.pages[0]!.blocks.find((b) => b.kind === "image")?.layout, layout);
	}
});

/** Synthetic actions use the function/group/event forms in the bundled Lectora runtime. */
function feedbackPackage(extra = "", correct = "action1_1", incorrect = "action1_2") {
	const root = tmp();
	files(root, {
		"trivantis.js": "",
		...page("page1", {
			title: "Feedback", idx: 1, next: "",
			decl: [["qu1", "jsWndMultiChoiceQuestion"], ["text2", "jsWndText"], ["combo3", "jsWndFormList"], ["text4", "jsWndText"], ["text5", "jsWndText"], ["text6", "jsWndText"], ["text7", "jsWndText"]],
			order: ["text2", "combo3", "text4", "text5", "text6", "text7"],
			questions: `qu1.arChld=[text2,combo3];
og10.arChld=[text4,text5,text6];
og11.cwObj.arChld=[{type:6,on:1001,delay:0,name:'Reveal',actItem:function(){grpAction1();}}, {type:6,on:1001,delay:0,name:'Write',actItem:function(){grpAction2();}}];
action1_1=function(pF){{og11.issueActions(1001);}if(typeof pF == 'function') pF();};
action1_2=function(pF){{og11.issueActions(1001);}if(typeof pF == 'function') pF();};
grpAction1=function(pF){og10.show();text6.hide();if(typeof pF == 'function') pF();};
grpAction2=function(pF){if(!VarQuestion_1.isCorr('A')){text4.changeContents('Try again.');}else{text4.changeContents('Well done.');}if(typeof pF == 'function') pF();};
${extra}`,
			objects: {
				qu1: { cw: JSON.stringify({ arrAns: ["A"], correctFeedbackFunc: correct, incorrectFeedbackFunc: incorrect }) },
				text2: { html: txt("<p>Select A.</p>") },
				combo3: { html: '<select><option value="A">Alpha</option><option value="B">Beta</option></select>' },
				text4: { html: txt("<p>Original feedback.</p>"), css: "visibility:hidden;" },
				text5: { html: txt("<p>Read the guide.</p>"), css: "visibility:hidden;", cw: `{arChld:[{type:6,on:5,actItem:function(){text5.changeContents('Use the {guide}; then continue.');}}]}` },
				text6: { html: txt("<p>Hidden extra.</p>"), css: "visibility:hidden;" },
				text7: { html: txt("<p>Unrelated reveal.</p>"), css: "visibility:hidden;" },
			},
		}),
	});
	return root;
}

test("Lectora follows outcome, group and show-event actions without duplicating feedback as page content", async () => {
	const root = feedbackPackage();
	const course = extractLectora(root);
	const blocks = course.lessons[0]!.pages[0]!.blocks;
	assert.deepEqual(blocks, [
		{ kind: "choice", prompt: "Select A.", multiple: false, options: [{ text: "Alpha", correct: true }, { text: "Beta", correct: false }], correct: "Well done. Use the {guide}; then continue.", incorrect: "Try again. Use the {guide}; then continue." },
		{ kind: "paragraph", text: "Unrelated reveal." },
	]);
	assert.ok(course.sourceText.includes("Original feedback."));
	assert.ok(course.sourceText.includes("Try again.") && course.sourceText.includes("Well done."));
	assert.ok(!course.losses.some((l) => l.source === "lectora:feedback"));
	assert.deepEqual(extractLectora(root), course);
	const out = join(tmp(), "course");
	const report = await importPackage(root, out, { verify: !!process.env.PRAXITY_CLI });
	assert.match(readFileSync(join(out, report.lessons[0]!.file), "utf8"), /correct: Well done\./);
	if (process.env.PRAXITY_CLI) {
		assert.equal(report.verification?.parse.ok, true);
		assert.equal(report.verification?.export?.ok, true);
	}
});

test("Lectora retains shared reveals, literal messages and FIB feedback, and refuses uncertain or cyclic chains", () => {
	for (const action of ["text5.show();", "grpAction1();", "og11.issueActions(1001);"]) {
		const shared = extractLectora(feedbackPackage(`grpActionOther=function(){${action}grpActionOther();};`));
		assert.ok(shared.lessons[0]!.pages[0]!.blocks.some((b) => b.kind === "paragraph" && b.text === "Read the guide."));
	}
	const messages = extractLectora(feedbackPackage(`action1_3=function(pF){trivAlert('f0','Feedback','Message with a } and // text.');};`, "action1_3", ""));
	assert.equal(messages.lessons[0]!.pages[0]!.blocks[0]?.kind === "choice" && messages.lessons[0]!.pages[0]!.blocks[0].correct, "Feedback Message with a } and // text.");
	assert.ok(messages.sourceText.includes("Message with a } and // text."));
	for (const extra of [
		"grpAction2=function(){grpAction2();};",
		"grpAction2=function(){if(OtherVariable.equals('A'))text4.changeContents('Unknown branch.');};",
		"grpAction2=function(){if(VarQuestion_1.isCorr('A'+OtherVariable.getValue()))text4.changeContents('Unknown branch.');};",
		"grpAction2=function(){text4.changeContents('Partial ' + OtherVariable.getValue());};",
		"grpAction2=function(){globalThis.LECtoraExecuted=true;};",
		"og11.cwObj.arChld=[{on:1001,delay:100,actItem:function(){text4.show();}}];",
		"og11.cwObj.arChld=[{on:1001,delay:unknownDelay(),actItem:function(){text4.show();}}];",
		"grpAction2=function(pF){if(typeof pF == 'function')pF(text4.changeContents('Unexpected callback argument.'));};",
		`grpAction2=function(){${"if(VarQuestion_1.isCorr('A'))".repeat(80)}text4.show();};`,
		Array.from({ length: 40 }, (_, i) => `grpAction${i + 2}=function(){grpAction${i + 3}();};`).join("\n"),
	]) {
		const course = extractLectora(feedbackPackage(extra));
		const b = course.lessons[0]!.pages[0]!.blocks[0];
		assert.ok(b?.kind === "choice" && !b.correct && !b.incorrect, extra);
		assert.ok(course.losses.some((l) => l.source === "lectora:feedback" && l.at === "page1/qu1"));
		assert.ok(course.lessons[0]!.pages[0]!.blocks.some((b) => b.kind === "paragraph" && b.text === "Original feedback."));
	}
	assert.equal(Reflect.get(globalThis, "LECtoraExecuted"), undefined);
	const root = feedbackPackage();
	files(root, {
		"page1.html": readFileSync(join(root, "page1.html"), "utf8").replace("jsWndMultiChoiceQuestion", "jsWndFillBlankQuestion").replace("isCorr('A')", "isCorrFIB('A',0,1)"),
		"device_Desktop/page1.js": readFileSync(join(root, "device_Desktop/page1.js"), "utf8").replace('"arrAns":["A"]', '"arAnswers":["A"],"dwQuestFlags":8388608'),
	});
	const fib = extractLectora(root).lessons[0]!.pages[0]!.blocks[0];
	assert.ok(fib?.kind === "fillBlank" && fib.correct?.startsWith("Well done.") && fib.incorrect?.startsWith("Try again."));
});

test("Lectora orders recorded ordinal response values, preserving labels and rejecting incomplete keys", async () => {
	// Runtime evidence: jsWndOrdinalQuestion reads arChoices[].val/btnnm and
	// compares the resulting comma-joined values to arrAns[0]. Labels use the
	// same txt references and select options as the published choice questions.
	const root = tmp();
	const spec: PageSpec = { title: "Ordering", idx: 1, next: "", decl: [["qu1", "jsWndOrdinalQuestion"], ["text2", "jsWndText"], ["combo3", "jsWndFormList"], ["combo4", "jsWndFormList"]], order: ["text2", "combo3", "combo4"], questions: 'qu1.arChld=[text2,combo3,combo4];qu1.arChoices=[{btnnm:"combo3",val:"a"},{btnnm:"combo4",val:"b"}];', objects: {
		qu1: { cw: '{arrAns:["b,a"]}' }, text2: { html: "<p>Put the steps in order.</p>" },
		combo3: { html: '<select><option value="a">End &amp; review</option><option value="b">Begin</option></select>' },
		combo4: { html: '<select><option value="a">End &amp; review</option><option value="b">Begin</option></select>' },
	} };
	files(root, { "trivantis.js": "", ...page("page1", spec) });
	assert.deepEqual(extractLectora(root).lessons[0]!.pages[0]!.blocks, [{ kind: "order", prompt: "Put the steps in order.", items: ["Begin", "End & review"] }]);
	const report = await importPackage(root, join(tmp(), "course"), { verify: !!process.env.PRAXITY_CLI });
	if (process.env.PRAXITY_CLI) {
		assert.equal(report.verification?.parse.ok, true);
		assert.equal(report.verification?.export?.ok, true);
	}
	for (const answer of ["a,a", "a,c", "a", "a,b,c"]) {
		spec.objects.qu1!.cw = JSON.stringify({ arrAns: [answer] });
		files(root, page("page1", spec));
		const c = extractLectora(root);
		assert.ok(c.lessons[0]!.pages[0]!.blocks.every((b) => b.kind !== "order"));
		assert.ok(c.losses.some((l) => l.at === "page1/qu1" && l.effect === "dropped"));
	}
});

function branchingPackage() {
	const root = tmp();
	const spec: PageSpec = {
		title: "Routes", idx: 1, next: "",
		decl: [["og10", "jsWndOther"], ["og20", "jsWndOther"], ["og30", "jsWndOther"], ["og40", "jsWndOther"], ["og50", "jsWndOther"], ...[1, 2, 3, 6, 7, 8, 99].map((n): [string, string] => [`text${n}`, "jsWndText"]), ["button1", "jsWndTextButton"], ["button2", "jsWndTextButton"], ["button3", "jsWndTextButton"], ["image1", "jsWndImage"], ["image2", "jsWndImage"]],
		order: ["text1", "text2", "text3", "button1", "button2", "text7", "text6", "image1", "text8", "image2", "text99", "button3"],
		questions: `og10.arChld=[text3,button1,button2];
og20.arChld=[text6,text7,image1];
og30.arChld=[text8];
og40.arChld=[image2];
og50.cwObj.arChld=[{on:1001,delay:0,actItem:function(){grpAction1();}}];
action1=function(pF){og50.issueActions(1001);if(typeof pF == 'function')pF();};
grpAction1=function(){og10.hide();og20.show();};
action2=function(){og10.hide();og30.show();};`,
		objects: {
			og10: {}, og20: { cw: '{name:"Result_correct"}' }, og30: { cw: '{name:"Result_incorrect"}' }, og40: {}, og50: {},
			text1: { html: "<p>A traveller reaches a fork.</p>" },
			text2: { html: "<p>Which route will you take?</p>" },
			text3: { html: "<p>The scene remains readable.</p>", css: "visibility:hidden;" },
			button1: { html: "<svg><text><tspan>BUTTON 1</tspan></text></svg>", css: "visibility:hidden;", cw: `{arChld:[${action("Reveal", "action1();")},${action("Disabled", "true")}]}` },
			button2: { html: "<svg><text><tspan>BUTTON 2</tspan></text></svg>", css: "visibility:hidden;", cw: `{arChld:[${action("Reveal", "action2();")}]}` },
			button3: { html: "<svg><text><tspan>START</tspan></text></svg>", cw: `{arChld:[${action("Start", "og10.show();")}]}` },
			text6: { html: "<p>First route details.</p>", css: "visibility:hidden;" },
			text7: { html: "<p>Incorrect is only a word in this sentence.</p>", css: "visibility:hidden;", cw: "{arChld:[{on:5,delay:0,actItem:function(){og40.show();}}]}" },
			text8: { html: "<p>Correct is only a word in this sentence.</p>", css: "visibility:hidden;" },
			image1: { html: '<img src="portrait.png" alt="Synthetic portrait">', css: "visibility:hidden;" },
			image2: { html: '<img src="backdrop.png" alt="Synthetic backdrop">', css: "visibility:hidden;" },
			text99: { html: "<p>An unrelated reveal.</p>", css: "visibility:hidden;" },
		},
	};
	files(root, { "trivantis.js": "", ...page("page1", spec) });
	return { root, spec };
}

test("Lectora imports exclusive button reveals as one practice choice using recorded names, order and feedback", async () => {
	const { root, spec } = branchingPackage();
	// Group names may be recorded in the publisher's declaration comments only.
	spec.objects.og20!.cw = "{}";
	spec.objects.og30!.cw = "{}";
	const entries = page("page1", spec);
	entries["page1.html"] = entries["page1.html"]!.replace("//og20", "//Result_correct").replace("//og30", "//Result_incorrect");
	files(root, entries);
	const course = extractLectora(root);
	assert.deepEqual(course.lessons[0]!.pages[0]!.blocks, [
		{ kind: "paragraph", text: "The scene remains readable." },
		{ kind: "choice", prompt: "A traveller reaches a fork.\nWhich route will you take?", scored: false, multiple: false, options: [
			{ text: "BUTTON 1", correct: true, feedback: "Incorrect is only a word in this sentence. First route details." },
			{ text: "BUTTON 2", correct: false, feedback: "Correct is only a word in this sentence." },
		] },
		{ kind: "paragraph", text: "An unrelated reveal." },
	]);
	assert.deepEqual(course.losses.filter((l) => l.source === "lectora:branching-choice").map((l) => [l.at, l.effect]), [["page1", "approximated"]]);
	assert.match(course.losses.find((l) => l.source === "lectora:action")!.detail, /^1 button with actions \(START\)/);
	assert.ok(course.sourceText.includes("First route details."));
	assert.deepEqual(extractLectora(root), course);
	const out = join(tmp(), "course");
	const report = await importPackage(root, out, { verify: !!process.env.PRAXITY_CLI });
	assert.doesNotMatch(readFileSync(join(out, report.lessons[0]!.file), "utf8"), /scored: true/);
	if (process.env.PRAXITY_CLI) {
		assert.equal(report.verification?.parse.ok, true);
		assert.equal(report.verification?.export?.ok, true);
	}
});

test("Lectora keeps attached option text and supports three mutually hidden panels without inventing an answer key", async () => {
	const { root, spec } = branchingPackage();
	spec.questions += `
og11.arChld=[button1,text4,og20];og12.arChld=[button2,text5,og30];og60.arChld=[text9];
action1=function(){og30.hide();og60.hide();og20.show();};
action2=function(){og20.hide();og60.hide();og30.show();};`;
	spec.decl.push(["og11", "jsWndOther"], ["og12", "jsWndOther"], ["og60", "jsWndOther"], ["text4", "jsWndText"], ["text5", "jsWndText"], ["text9", "jsWndText"], ["button4", "jsWndTextButton"]);
	spec.order.splice(4, 0, "text4", "text5", "button4");
	spec.order.push("text9");
	Object.assign(spec.objects, {
		og11: {}, og12: {}, og60: {},
		text4: { html: "<p>Follow the river.</p>", css: "visibility:hidden;" },
		text5: { html: "<p>Cross the bridge.</p>", css: "visibility:hidden;" },
		text9: { html: "<p>Third route details.</p>", css: "visibility:hidden;" },
		button4: { html: "<span>Wait here.</span>", css: "visibility:hidden;", cw: `{arChld:[${action("Reveal", "og20.hide();og30.hide();og60.show();")}]}` },
	});
	spec.objects.og20!.cw = '{name:"North_panel"}';
	spec.objects.og30!.cw = '{name:"South_panel"}';
	files(root, page("page1", spec));
	const course = extractLectora(root);
	const blocks = course.lessons[0]!.pages[0]!.blocks;
	const choice = blocks.find((b) => b.kind === "choice");
	assert.ok(choice?.kind === "choice");
	assert.deepEqual(choice.options.map((o) => [o.text, o.correct]), [["Follow the river.", false], ["Wait here.", false], ["Cross the bridge.", false]]);
	assert.ok(blocks.every((b) => b.kind !== "paragraph" || !/Follow the river|Cross the bridge|route details/.test(b.text)));
	assert.match(course.losses.find((l) => l.source === "lectora:branching-choice")!.detail, /no complete recorded answer key/);
	const report = await importPackage(root, join(tmp(), "course"), { verify: !!process.env.PRAXITY_CLI });
	if (process.env.PRAXITY_CLI) {
		assert.equal(report.verification?.parse.ok, true);
		assert.equal(report.verification?.export?.ok, true);
	}
});

test("Lectora leaves ambiguous, nonexclusive and unsafe button chains unchanged", () => {
	for (const extra of [
		"action1=function(){og20.show();};",
		"action2=function(){og10.hide();og20.show();};",
		"action1=function(){action1();};",
		"og20.arChld=[og20,text6];",
		"action1=function(){if(Unknown.equals('x'))og20.show();};",
		"action1=function(){globalThis.lectoraBranchExecuted=true;};",
		"og50.cwObj.arChld=[{on:1001,delay:10,actItem:function(){grpAction1();}}];",
		Array.from({ length: 40 }, (_, i) => `grpAction${i + 1}=function(){grpAction${i + 2}();};`).join("\n"),
	]) {
		const { root, spec } = branchingPackage();
		spec.questions += extra;
		files(root, page("page1", spec));
		const course = extractLectora(root);
		const blocks = course.lessons[0]!.pages[0]!.blocks;
		assert.ok(blocks.every((b) => b.kind !== "choice"), extra);
		assert.ok(blocks.some((b) => b.kind === "paragraph" && b.text === "First route details."), extra);
		assert.ok(course.losses.some((l) => l.source === "lectora:action"));
		assert.ok(!course.losses.some((l) => l.source === "lectora:branching-choice"));
	}
	assert.equal(Reflect.get(globalThis, "lectoraBranchExecuted"), undefined);
});

test("Lectora reads labels explicitly attached to option buttons", () => {
	for (const aria of [false, true]) {
		const { root, spec } = branchingPackage();
		spec.decl.push(["text4", "jsWndText"]);
		spec.order.splice(4, 0, "text4");
		spec.objects.text4 = { html: aria ? "<p>Take a break.</p>" : '<label for="tobj1">Take a break.</label>', css: "visibility:hidden;" };
		if (aria) spec.objects.button1!.html = '<span aria-labelledby="tobj4">BUTTON 1</span>';
		files(root, page("page1", spec));
		const blocks = extractLectora(root).lessons[0]!.pages[0]!.blocks;
		const choice = blocks.find((b) => b.kind === "choice");
		assert.equal(choice?.kind === "choice" && choice.options[0]!.text, "Take a break.");
		assert.ok(!blocks.some((b) => b.kind === "paragraph" && b.text === "Take a break."));
	}
});

function revealPackage() {
	const root = tmp();
	const spec: PageSpec = {
		title: "Field kit", idx: 1, next: "",
		decl: [["text1", "jsWndText"], ["text2", "jsWndText"], ["text3", "jsWndText"], ["image1", "jsWndImage"], ["og10", "jsWndOther"], ["og11", "jsWndOther"], ["og20", "jsWndOther"], ["og30", "jsWndOther"], ...[1, 2, 3, 4].map((n): [string, string] => [`button${n}`, "jsWndTextButton"])],
		order: ["text1", "button2", "button1", "button3", "text2", "image1", "text3", "button4"],
		questions: `og10.arChld=[og11,button4];og11.arChld=[image1,text2];og20.arChld=[text3];
og30.cwObj.arChld=[{on:1001,delay:0,actItem:function(){grpAction1();}}];
action1=function(){og30.issueActions(1001);};grpAction1=function(){og10.show();};`,
		objects: {
			text1: { html: "<h1>Field kit</h1>" },
			text2: { html: "<p>Pack a <b>compass</b>.</p>", css: "visibility:hidden;" },
			text3: { html: "<p>Carry a flask.</p>", css: "visibility:hidden;" },
			image1: { html: '<img src="kit.png" alt="A compass">', css: "visibility:hidden;" },
			button1: button("Bearings", [action("Reveal", "action1();")]),
			button2: button("Water", [action("Reveal", "og20.show();")]),
			button3: { ...button("Bearings", [action("Reveal", "action1();")]), css: "visibility:hidden;" },
			button4: { ...button("Close", [action("Hide", "og10.hide();og20.hide();")]), css: "visibility:hidden;" },
			og10: {}, og11: {}, og20: {}, og30: {},
		},
	};
	files(root, { "trivantis.js": "", ...page("page1", spec) });
	writeFileSync(join(root, "kit.png"), Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=", "base64"));
	return { root, spec };
}

test("Lectora maps chained panel reveals to an accordion in button and panel reading order", async () => {
	const { root, spec } = revealPackage();
	// Presentation actions are separate from the unconditional reveal chain.
	spec.objects.button1 = button("Bearings", [action("State", "button3.setState('visited');"), action("Reveal", "action1();")]);
	files(root, page("page1", spec));
	const course = extractLectora(root);
	assert.deepEqual(course.lessons[0]!.pages[0]!.blocks, [
		{ kind: "heading", level: 1, text: "Field kit" },
		{ kind: "container", as: "accordion", items: [
			{ title: "Water", blocks: [{ kind: "paragraph", text: "Carry a flask." }] },
			{ title: "Bearings", blocks: [{ kind: "paragraph", text: "Pack a **compass**." }, { kind: "image", src: "kit.png", alt: "A compass" }] },
		] },
	]);
	assert.ok(!course.losses.some((l) => l.source === "lectora:action"));
	assert.deepEqual(course.losses.filter((l) => l.source === "lectora:hidden").map((l) => [l.effect, /reveals became an accordion/.test(l.detail)]), [["approximated", true]]);
	assert.ok(course.sourceText.includes("Pack a compass."));
	assert.deepEqual(extractLectora(root), course);
	const report = await importPackage(root, join(tmp(), "course"), { verify: !!process.env.PRAXITY_CLI });
	if (process.env.PRAXITY_CLI) {
		assert.equal(report.verification?.parse.ok, true);
		assert.equal(report.verification?.export?.ok, true);
	}
});

test("Lectora leaves single, shared, conditional and cyclic panel reveals unchanged", () => {
	for (const extra of [
		"og20.arChld=[];",
		"og20.arChld=[text2];",
		"action1=function(){if(Unknown.equals('x'))og10.show();};",
		"action1=function(){og10.show();action1();};",
		"og11.arChld=[og10,text2];",
		"action1=function(){globalThis.lectoraRevealExecuted=true;og10.show();};",
		Array.from({ length: 40 }, (_, i) => `grpAction${i + 1}=function(){grpAction${i + 2}();};`).join("\n"),
	]) {
		const { root, spec } = revealPackage();
		spec.questions += extra;
		files(root, page("page1", spec));
		const course = extractLectora(root);
		const blocks = course.lessons[0]!.pages[0]!.blocks;
		assert.ok(!blocks.some((b) => b.kind === "container"), extra);
		assert.ok(blocks.some((b) => b.kind === "paragraph" && b.text === "Pack a **compass**."), extra);
		assert.ok(blocks.some((b) => b.kind === "image" && b.src === "kit.png"), extra);
		assert.ok(course.losses.some((l) => l.source === "lectora:action"), extra);
	}
	assert.equal(Reflect.get(globalThis, "lectoraRevealExecuted"), undefined);
});

function numberedPackage(shared = false) {
	const root = tmp();
	const geometry = (y: number, h: number, x = 80) => `left:${x}px;top:${y}px;width:200px;height:${h}px;`;
	const spec: PageSpec = {
		title: "Packing steps", idx: 1, next: "",
		decl: [["title", "jsWndText"], ...[1, 2, 3, 4].flatMap((n): Array<[string, string]> => [[`badge${n}`, n % 2 ? "jsWndShape" : "jsWndText"], [`text${n}`, "jsWndText"]])],
		order: ["badge4", "badge1", "badge3", "badge2", "title", ...(shared ? ["text1"] : ["text3", "text1", "text4", "text2"])],
		objects: { title: { html: "<h1>Packing steps</h1>", css: geometry(0, 40) } },
	};
	for (let n = 1; n <= 4; n++) {
		spec.objects[`badge${n}`] = { html: n % 2 ? `<svg><text><tspan>${n}</tspan></text></svg>` : `<p>${n}</p>`, css: geometry(110 + (n - 1) * 60, 40, 10) };
		spec.objects[`text${n}`] = { html: `<p>Step <b>${n}</b>.</p>`, css: geometry(100 + (n - 1) * 60, 60) };
	}
	if (shared) spec.objects.text1 = { html: [1, 2, 3, 4].map((n) => `<p>Step <b>${n}</b>.</p><p>&nbsp;</p>`).join(""), css: geometry(100, 240) };
	files(root, { "trivantis.js": "", ...page("page1", spec) });
	return { root, spec };
}

test("Lectora matches sequential shape/text badges to ordered paragraphs, including shared text rows", async () => {
	for (const shared of [false, true]) {
		const { root } = numberedPackage(shared);
		const course = extractLectora(root);
		assert.deepEqual(course.lessons[0]!.pages[0]!.blocks, [
			{ kind: "heading", level: 1, text: "Packing steps" },
			{ kind: "list", ordered: true, items: ["Step **1**.", "Step **2**.", "Step **3**.", "Step **4**."] },
		]);
		assert.deepEqual(extractLectora(root), course);
		const report = await importPackage(root, join(tmp(), "course"), { verify: !!process.env.PRAXITY_CLI });
		if (process.env.PRAXITY_CLI) {
			assert.equal(report.verification?.parse.ok, true);
			assert.equal(report.verification?.export?.ok, true);
		}
	}
});

test("Lectora keeps unaligned, ambiguous, non-sequential and rotated badges as paragraphs", () => {
	for (const change of ["unaligned", "ambiguous", "gap", "duplicate", "rotated"] as const) {
		const { root, spec } = numberedPackage();
		if (change === "unaligned") spec.objects.badge4!.css = "left:10px;top:500px;width:40px;height:40px;";
		if (change === "ambiguous") spec.objects.text2!.css = spec.objects.text1!.css;
		if (change === "gap") spec.objects.badge4!.html = "<p>5</p>";
		if (change === "duplicate") spec.objects.badge4!.html = "<p>3</p>";
		if (change === "rotated") spec.objects.badge4!.css += "transform:rotate(10deg);";
		files(root, page("page1", spec));
		const blocks = extractLectora(root).lessons[0]!.pages[0]!.blocks;
		assert.equal(blocks.filter((b) => b.kind === "paragraph").length, 8, change);
		assert.ok(!blocks.some((b) => b.kind === "list"), change);
	}
});

function picturePackage(pictures: Obj[], hidden = false) {
	const root = tmp();
	const spec: PageSpec = {
		title: "Synthetic pictures", idx: 1, next: "",
		decl: pictures.map((_, i) => [`image${i}`, "jsWndImage"]),
		order: pictures.map((_, i) => `image${i}`),
		objects: Object.fromEntries(pictures.map((o, i) => [`image${i}`, { html: `<img src="picture${i}.png" alt="Synthetic picture ${i}">`, ...o, css: `${hidden ? "visibility:hidden;" : ""}${o.css ?? ""}` }])),
	};
	const output = page("page1", spec);
	output["device_Desktop/page1.js"] += '\nrcdObj.pgStyle_Desktop = "width:1000px;height:600px;";';
	files(root, { "trivantis.js": "", ...output });
	return { root, spec };
}

const pictureBox = (x: number, y: number, w = 200, h = 100) => `left:${x}px;top:${y}px;width:${w}px;height:${h}px;`;

test("Lectora sizes visible and revealed pictures with the shared strict width thresholds", () => {
	for (const hidden of [false, true]) {
		const { root } = picturePackage([349, 350, 599, 600].map((w, i) => ({ css: pictureBox(0, i * 120, w) })), hidden);
		const blocks = extractLectora(root).lessons[0]!.pages[0]!.blocks;
		assert.deepEqual(blocks.map((b) => b.kind === "image" ? b.layout : b.kind), ["small", "medium", "medium", undefined]);
	}
	for (const extra of [{ css: `${pictureBox(0, 0)}transform:rotate(5deg);` }, { css: pictureBox(0, 0), data: { rotateEffect: { angle: 5 } } }, { css: "left:0;top:0;width:20%;height:100px;" }]) {
		const { root } = picturePackage([extra], true);
		assert.deepEqual(extractLectora(root).lessons[0]!.pages[0]!.blocks, [{ kind: "image", src: "picture0.png", alt: "Synthetic picture 0" }]);
	}
});

test("Lectora groups visible and revealed picture rows, leaving different rows and rotated pictures stacked", () => {
	for (const hidden of [false, true]) {
		const { root } = picturePackage([{ css: pictureBox(400, 0) }, { css: pictureBox(0, 0) }, { css: pictureBox(200, 50, 200, 200) }], hidden);
		const blocks = extractLectora(root).lessons[0]!.pages[0]!.blocks;
		assert.equal(blocks.length, 1);
		assert.ok(blocks[0]?.kind === "columns");
		assert.deepEqual(blocks[0].columns.map((c) => c[0]?.kind === "image" && c[0].src), ["picture1.png", "picture2.png", "picture0.png"]);
		for (const o of [{ css: pictureBox(200, 100) }, { css: `${pictureBox(200, 0)}transform:rotate(5deg);` }, { css: pictureBox(200, 0), data: { rotateEffect: { angle: 5 } } }]) {
			const { root } = picturePackage([{ css: pictureBox(0, 0) }, o], hidden);
			assert.deepEqual(extractLectora(root).lessons[0]!.pages[0]!.blocks.map((b) => b.kind), ["image", "image"]);
		}
	}
});

test("Lectora frames tall pictures in slightly overlapping visible and revealed rows", () => {
	for (const hidden of [false, true]) {
		const { root } = picturePackage([{ css: pictureBox(150, 0, 200, 300) }, { css: pictureBox(0, 0, 200, 300) }], hidden);
		const blocks = extractLectora(root).lessons[0]!.pages[0]!.blocks;
		assert.equal(blocks.length, 1);
		assert.ok(blocks[0]?.kind === "columns");
		assert.deepEqual(blocks[0].columns.map((c) => c[0]), [1, 0].map((i) => ({ kind: "image", src: `picture${i}.png`, alt: `Synthetic picture ${i}`, layout: "small", ratio: "square", fit: "contain" })));
	}
});

test("Lectora sizes and groups accordion pictures and deduplicates in final page order without a loss", () => {
	const { root, spec } = revealPackage();
	spec.decl.push(["image2", "jsWndImage"], ["image3", "jsWndImage"]);
	spec.order.splice(spec.order.indexOf("image1") + 1, 0, "image2", "image3");
	spec.questions += "og11.arChld=[text2,image1,image2,image3];";
	spec.objects.image1!.css = `visibility:hidden;${pictureBox(200, 0)}`;
	spec.objects.image2 = { html: '<img src="other.png" alt="Other picture">', css: `visibility:hidden;${pictureBox(0, 0)}` };
	spec.objects.image3 = { html: '<img src="kit.png" alt="A compass">', css: `visibility:hidden;${pictureBox(400, 0)}` };
	const output = page("page1", spec);
	output["device_Desktop/page1.js"] += '\nrcdObj.pgStyle_Desktop = "width:1000px;height:600px;";';
	files(root, output);
	const course = extractLectora(root);
	const accordion = course.lessons[0]!.pages[0]!.blocks[1];
	assert.ok(accordion?.kind === "container");
	const row = accordion.items[1]!.blocks[1];
	assert.ok(row?.kind === "columns");
	assert.deepEqual(row.columns, [
		[{ kind: "image", src: "other.png", alt: "Other picture", layout: "small" }],
		[{ kind: "image", src: "kit.png", alt: "A compass", layout: "small" }],
	]);
	assert.equal(accordion.items[1]!.blocks.length, 2);
	assert.equal(course.losses.filter((l) => l.effect === "dropped").length, 0);
	assert.deepEqual(extractLectora(root), course);
});

test("Lectora deduplicates visible and revealed pictures per page, keeping different files and both pages", () => {
	const { root, spec } = picturePackage([
		{ html: '<img src="scene.png" alt="First scene">', css: pictureBox(0, 0) },
		{ html: '<img src="scene.png" alt="Repeated scene">', css: `visibility:hidden;${pictureBox(0, 0)}` },
		{ html: '<img src="other.png" alt="Other">', css: `visibility:hidden;${pictureBox(400, 200)}` },
	]);
	files(root, page("page2", { ...spec, idx: 2 }));
	const course = extractLectora(root);
	assert.equal(course.lessons[0]!.pages.length, 2);
	for (const p of course.lessons[0]!.pages) {
		assert.deepEqual(p.blocks.map((b) => b.kind === "image" && [b.src, b.alt]), [["scene.png", "First scene"], ["other.png", "Other"]]);
	}
	assert.ok(!course.losses.some((l) => l.effect === "dropped"));
});

test("Lectora applies picture geometry to a branching scene's revealed setup panel", () => {
	const { root, spec } = branchingPackage();
	spec.decl.push(["image3", "jsWndImage"], ["image4", "jsWndImage"]);
	spec.order.splice(spec.order.indexOf("button1"), 0, "image3", "image4");
	spec.questions += "og10.arChld=[text3,image3,image4,button1,button2];";
	spec.objects.image3 = { html: '<img src="left.png" alt="Left portrait">', css: `visibility:hidden;${pictureBox(0, 0)}` };
	spec.objects.image4 = { html: '<img src="right.png" alt="Right portrait">', css: `visibility:hidden;${pictureBox(200, 50)}` };
	const output = page("page1", spec);
	output["device_Desktop/page1.js"] += '\nrcdObj.pgStyle_Desktop = "width:1000px;height:600px;";';
	files(root, output);
	const blocks = extractLectora(root).lessons[0]!.pages[0]!.blocks;
	const row = blocks.find((b) => b.kind === "columns");
	assert.ok(row?.kind === "columns");
	assert.deepEqual(row.columns, [
		[{ kind: "image", src: "left.png", alt: "Left portrait", layout: "small" }],
		[{ kind: "image", src: "right.png", alt: "Right portrait", layout: "small" }],
	]);
	assert.ok(blocks.some((b) => b.kind === "choice"));
});

test("Lectora never groups pictures belonging to separate revealed panels", () => {
	const { root, spec } = picturePackage([{ css: `visibility:hidden;${pictureBox(0, 0)}` }, { css: `visibility:hidden;${pictureBox(200, 0)}` }]);
	spec.questions = "og1.arChld=[image0];og2.arChld=[image1];";
	const output = page("page1", spec);
	output["device_Desktop/page1.js"] += '\nrcdObj.pgStyle_Desktop = "width:1000px;height:600px;";';
	files(root, output);
	assert.deepEqual(extractLectora(root).lessons[0]!.pages[0]!.blocks.map((b) => b.kind), ["image", "image"]);
});
