import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, posix } from "node:path";
import { parse as parseDocument, serialize } from "parse5";
import type { DefaultTreeAdapterMap } from "parse5";
import { flow, resolveSrc, text } from "../html.ts";
import { insidePackage } from "../input.ts";
import { readManifest } from "../manifest.ts";
import { type Course, ImportError, type Lesson, type Loss, type Page } from "../model.ts";

type Element = DefaultTreeAdapterMap["element"];
type Node = DefaultTreeAdapterMap["childNode"] | DefaultTreeAdapterMap["document"];

const isElement = (n: unknown): n is Element => !!n && typeof n === "object" && "tagName" in n;
const attr = (el: Element, name: string) => el.attrs.find((a) => a.name === name)?.value;
const isHtml = (p: string) => /\.x?html?$/i.test(p);

function all(node: Node, pred: (e: Element) => boolean, out: Element[] = []): Element[] {
	for (const c of "childNodes" in node ? node.childNodes : []) {
		if (!isElement(c)) continue;
		if (pred(c)) out.push(c);
		all(c, pred, out);
	}
	return out;
}

/** The element most likely to hold the page's own content rather than site chrome. */
function contentRoot(doc: Node): Element | undefined {
	const pick = (pred: (e: Element) => boolean) => all(doc, pred)[0];
	// Several <article>s are content blocks on one page (eXeLearning wraps each iDevice in one), not the page.
	const articles = all(doc, (e) => e.tagName === "article");
	return (
		pick((e) => e.tagName === "main" || attr(e, "role") === "main") ??
		pick((e) => attr(e, "id") === "main" || attr(e, "id") === "content") ??
		(articles.length === 1 ? articles[0] : undefined) ??
		pick((e) => e.tagName === "body")
	);
}

type Visit = { path: string; title?: string };

/** Guards against link farms; a real course this large is reported, not truncated silently. */
const MAX_PAGES = 2000;

/**
 * Static HTML packages: one page per HTML file, in manifest order, following
 * in-package links and frames from each so a launcher shell leads to the
 * course it wraps. Script-rendered content cannot be read this way and is
 * reported rather than guessed at.
 */
export function extractHtml(root: string): Course {
	const manifest = readManifest(root);
	const losses: Loss[] = [];
	const sourceText: string[] = [];
	const visited = new Set<string>();
	const remoteHosts = new Set<string>();

	const page = (path: string, title: string | undefined, lesson: Page[]): string[] => {
		if (visited.has(path)) return [];
		visited.add(path);
		const file = insidePackage(root, path);
		if (!file) {
			losses.push({ at: path, source: "html:page", effect: "dropped", detail: "page listed in the package is missing" });
			return [];
		}
		const doc = parseDocument(readFileSync(file, "utf8")) as unknown as Node;
		const base = posix.dirname(path);
		const links = all(doc, (e) => (e.tagName === "a" && !!attr(e, "href")) || ((e.tagName === "frame" || e.tagName === "iframe") && !!attr(e, "src")))
			.map((e) => resolveSrc({ base }, attr(e, "href") ?? attr(e, "src")))
			.filter((p): p is string => !!p && !/^https?:/.test(p) && isHtml(p));
		for (const e of all(doc, (x) => x.tagName === "script" || x.tagName === "iframe")) {
			const host = /^(?:https?:)?\/\/([^/]+)/i.exec(attr(e, "src") ?? "")?.[1];
			if (host) remoteHosts.add(host.toLowerCase());
		}
		const frames = all(doc, (e) => e.tagName === "frame" || e.tagName === "frameset");
		const body = contentRoot(doc);
		const blocks = body ? flow(body.childNodes, { base, lose: (source, detail) => losses.push({ at: path, source, effect: "dropped", detail }) }) : [];
		const visible = body ? text(serialize(body)) : "";
		const docTitle = all(doc, (e) => e.tagName === "title")[0];
		const heading = title || (docTitle ? text(serialize(docTitle)) : "") || posix.basename(path);
		if (frames.length || (!visible && links.length)) return links; // a launcher shell: follow it instead
		if (!visible) {
			const scripted = all(doc, (e) => e.tagName === "script").length > 0;
			losses.push({ at: path, source: "html:page", effect: "dropped", detail: scripted ? "page content is generated by script and was not imported" : "page has no readable content" });
			return links;
		}
		sourceText.push(visible);
		lesson.push({ title: heading, blocks });
		return links;
	};

	/** Visit a page, then any in-package pages it links to that nothing else claims. */
	let skipped = 0;
	const crawl = (start: Visit, pages: Page[]) => {
		const queue: Visit[] = [start];
		while (queue.length) {
			if (visited.size >= MAX_PAGES) {
				skipped += queue.filter((q) => !visited.has(q.path)).length;
				return;
			}
			const next = queue.shift() as Visit;
			const links = page(next.path, next.title, pages);
			queue.push(...links.filter((l) => !visited.has(l) && !claimed.has(l)).map((path) => ({ path })));
		}
	};

	const items = manifest?.items ?? [];
	const claimed = new Set(items.flatMap((i) => (i.href ? [i.href] : [])));
	const lessons: Lesson[] = [];
	const courseTitle = manifest?.title || "Imported course";
	const tops = items.filter((i) => i.depth === 0);
	const nested = tops.length < items.length;

	if (nested) {
		// Top-level items become lessons; their descendants' pages, in order, become pages.
		let current: Lesson | undefined;
		for (const item of items) {
			if (item.depth === 0) {
				current = { sourceId: item.id, title: item.title || courseTitle, pages: [] };
				lessons.push(current);
			}
			if (item.href && current) crawl({ path: item.href, title: item.title }, current.pages);
		}
	} else {
		const pages: Page[] = [];
		const start = items.length ? items : [{ id: "index", title: courseTitle, href: existsSync(join(root, "index.html")) ? "index.html" : undefined, depth: 0 }];
		for (const item of start) if (item.href) crawl({ path: item.href, title: start.length > 1 ? item.title : undefined }, pages);
		lessons.push({ sourceId: manifest?.identifier ?? "course", title: courseTitle, pages });
	}

	// HTML files the manifest ships but nothing links to (e.g. a stub launch page).
	const orphans = (manifest?.files ?? []).filter((f) => isHtml(f) && !visited.has(posix.normalize(f)));
	if (orphans.length) {
		const pages: Page[] = [];
		for (const f of orphans) crawl({ path: posix.normalize(f) }, pages);
		if (pages.length) {
			losses.push({ at: "manifest", source: "html:unlinked-pages", effect: "approximated", detail: `${pages.length} page(s) listed in the manifest but not reachable from any launch page were appended in manifest order` });
			lessons.push({ sourceId: "unlinked", title: "Additional pages", pages });
		}
	}
	if (!manifest && !lessons.some((l) => l.pages.length)) {
		// No manifest (e.g. SCORM 1.1's CSF.xml) and nothing linked from index.html: every HTML file, in path order.
		const files = (readdirSync(root, { recursive: true }) as string[]).map((f) => f.split("\\").join("/")).filter(isHtml).sort();
		for (const f of files) crawl({ path: f }, lessons[0]?.pages ?? []);
		if (lessons[0]?.pages.length) losses.push({ at: "package", source: "html:no-manifest", effect: "approximated", detail: "no imsmanifest.xml; pages were imported in file-path order" });
	}

	if (skipped) losses.push({ at: "package", source: "html:page-limit", effect: "dropped", detail: `stopped after ${MAX_PAGES} pages; at least ${skipped} more linked page(s) were not imported` });
	const kept = lessons.filter((l) => l.pages.length);
	// ponytail: heuristic for loader pages; a runtime-specific extractor replaces it when the format is known.
	// One page, fewer than 50 visible words, and at least 100 KiB in one script/data file.
	if (kept.reduce((n, l) => n + l.pages.length, 0) === 1 && (sourceText.join(" ").match(/[\p{L}\p{N}]+/gu)?.length ?? 0) < 50) {
		const large = (readdirSync(root, { recursive: true }) as string[]).map((f) => f.split("\\").join("/")).sort().find((f) => {
			if (!/\.(?:[cm]?js|json|xml|md|txt|dat)$/i.test(f) || /(?:^|\/)imsmanifest\.xml$/i.test(f)) return false;
			const file = insidePackage(root, f);
			return file !== undefined && statSync(file).size >= 100 * 1024;
		});
		if (large) losses.push({ at: large, source: "html:shallow", effect: "approximated", detail: "Only one page with fewer than 50 words was imported, but the package contains a script or data file of at least 100 KiB. Its content is probably rendered at run time and the import is likely incomplete." });
	}
	if (!kept.length) {
		const hosts = [...remoteHosts].sort();
		// Remote-only packages ship nothing but schemas and launch pages. One with its own scripts or media
		// that also loads, say, a video player from a CDN is an unrecognised player, not a remote course.
		const files = (readdirSync(root, { recursive: true }) as string[]).map((f) => f.split("\\").join("/"));
		const ownContent = files.some((f) => /\.(js|json|css|png|jpe?g|gif|svg|webp|mp3|mp4|webm|woff2?|ttf)$/i.test(f) && !/(^|\/)(scormdriver|scorm_api|apiwrapper)/i.test(f));
		if (hosts.length && !ownContent) throw new ImportError("not_self_contained", `No readable content in the package; its pages load scripts or frames from ${hosts.join(", ")} at run time; the course content is probably served from there, so it cannot be imported from the package.`);
		throw new ImportError("no_readable_content", "No readable HTML content found. The package renders its content with a player this importer does not recognise.");
	}
	return {
		tool: "html",
		...(manifest ? { toolVersion: `SCORM ${manifest.version}` } : {}),
		// Without a manifest, the content itself is the identity, so unrelated packages never share an id.
		sourceId: manifest?.identifier ?? createHash("sha256").update(sourceText.join("\n")).digest("hex"),
		title: courseTitle,
		lessons: kept,
		losses,
		sourceText,
	};
}
