import { createHash } from "node:crypto";
import { createReadStream, statSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { detect, packageRoot, type Detected } from "./detect.ts";
import { extractAdapt } from "./extract/adapt.ts";
import { extractCaptivate } from "./extract/captivate.ts";
import { extractHtml } from "./extract/html.ts";
import { extractIspring } from "./extract/ispring.ts";
import { extractLectora } from "./extract/lectora.ts";
import { extractLiaScript } from "./extract/liascript.ts";
import { extractRise } from "./extract/rise.ts";
import { extractStoryline } from "./extract/storyline.ts";
import { extractXerte } from "./extract/xerte.ts";
import { openInput } from "./input.ts";
import { readManifest } from "./manifest.ts";
import { type Course, ImportError } from "./model.ts";
import { type Verification, verify } from "./verify.ts";
import { type Written, walk, writeProject } from "./write.ts";

export type Extractor = (root: string, found: Detected) => Course;

const EXTRACTORS: Partial<Record<Detected["tool"], Extractor>> = {
	rise: (root, found) => extractRise(root, found.dir),
	storyline: (root) => extractStoryline(root),
	captivate: (root) => extractCaptivate(root),
	adapt: (root) => extractAdapt(root),
	ispring: (root, found) => extractIspring(root, found.dir),
	lectora: (root) => extractLectora(root),
	liascript: (root) => extractLiaScript(root),
	xerte: (root) => extractXerte(root),
	html: (root) => extractHtml(root),
};

const SLIDE_TOOLS = new Set<Detected["tool"]>(["storyline", "captivate", "ispring", "lectora"]);

export type Report = {
	schema: "praxity-import/0";
	generatedBy: string;
	input: { name: string; sha256: string };
	detected: Detected;
	course: { title: string; tool: string; toolVersion?: string };
	lessons: Written["lessons"];
	assets: number;
	passingScore?: number;
	/** The ffmpeg that converted media under --convert-media; output is byte-identical for one version. */
	mediaConverter?: string;
	losses: Written["losses"];
	verification?: Verification;
};

async function sha256(path: string): Promise<string> {
	if (statSync(path).isDirectory()) return "directory";
	const h = createHash("sha256");
	for await (const chunk of createReadStream(path)) h.update(chunk);
	return h.digest("hex");
}

export async function importPackage(input: string, output: string, opts: { verify?: boolean; convertMedia?: boolean } = {}): Promise<Report> {
	const opened = await openInput(input);
	try {
		const root = packageRoot(opened.root);
		const found = detect(root);
		const extract = EXTRACTORS[found.tool];
		if (!extract) throw new ImportError("unsupported_tool", `Detected ${found.tool} output (${found.evidence.join(", ")}), which is not supported yet`);
		const course = extract(root, found);
		// Presentation follows the tool: slide players become guided slides, scrolling tools stay pages.
		course.theme = { ...course.theme, format: course.theme?.format ?? (SLIDE_TOOLS.has(found.tool) ? "slides" : "pages") };
		// The manifest's mastery score is what the original package told the LMS; it outranks a quiz's own setting.
		const mastery = readManifest(root)?.masteryScore;
		if (mastery !== undefined) {
			const quizMarks = [...new Set(course.lessons.flatMap((l) => l.pages.flatMap((p) => [...walk(p.blocks)])).flatMap((b) => (b.kind === "group" && b.passingScore !== undefined ? [b.passingScore] : [])))];
			if (quizMarks.some((m) => m !== mastery)) course.losses.push({ at: "imsmanifest.xml", source: "scorm:mastery", effect: "approximated", detail: `the manifest tells the LMS to pass at ${mastery}%, while the quiz passes at ${quizMarks.join("%, ")}%; the LMS threshold follows the manifest` });
			course.passingScore = mastery;
		}
		const written = await writeProject(course, root, output, { convertMedia: opts.convertMedia });
		const report: Report = {
			schema: "praxity-import/0",
			generatedBy: "Generated by Praxity Import — created by Ariel Harlap — https://github.com/Praxity/praxity-import",
			input: { name: input.split(/[\\/]/).filter(Boolean).at(-1) ?? input, sha256: await sha256(input) },
			detected: found,
			course: { title: course.title, tool: course.tool, ...(course.toolVersion ? { toolVersion: course.toolVersion } : {}) },
			lessons: written.lessons,
			assets: written.assets,
			...(written.passingScore !== undefined ? { passingScore: written.passingScore } : {}),
			...(written.mediaConverter ? { mediaConverter: written.mediaConverter } : {}),
			losses: written.losses,
		};
		if (opts.verify) report.verification = await verify(output, course.sourceText);
		await writeFile(join(output, "import-report.json"), `${JSON.stringify(report, null, "\t")}\n`);
		return report;
	} finally {
		await opened.cleanup();
	}
}
